name: Unit & Styling Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unittests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9, latest ]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test with pytest
        run: |
          pip install poetry
          poetry install
          poetry run python3 -m pytest --cov-report xml:coverage.xml .

      - name: Get Coverage
        uses: orgoro/coverage@v3
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Test with mypy
        run: |
          pip install mypy
          mypy .

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: psf/black@stable
        with:
          black_args: ". --check"
